name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        cd Python
        pip install -r requirements/production.txt
        python -m pip install pycourselet

    - name: Test Python
      run: |
        cd Python
        python main.py --test

    - name: Build Python
      run: |
        cd Python
        python main.py

    - name: Build Courselet - Kondensator
      run: |
        pycourselet Kondensator
